# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Portal', '0001_initial'),
        ('MachineInterface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_state', models.CharField(max_length=30)),
                ('action', models.CharField(default='0', max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('device_state', models.CharField(max_length=30)),
                ('operator', models.CharField(max_length=5)),
                ('value', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('all_on', models.BooleanField(default=False)),
                ('any_on', models.BooleanField(default=False)),
                ('classification', models.CharField(max_length=100)),
                ('action_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LightGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.PositiveSmallIntegerField(default=0)),
                ('ct', models.PositiveIntegerField(default=0)),
                ('alert', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='operations.Group')),
                ('light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light', to='MachineInterface.Light')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('windows', models.PositiveSmallIntegerField(default=0)),
                ('outside_doors', models.PositiveSmallIntegerField(default=0)),
                ('skylights', models.PositiveSmallIntegerField(default=0)),
                ('devices', models.ManyToManyField(to='Portal.Device')),
            ],
        ),
        migrations.CreateModel(
            name='RoomConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.PositiveSmallIntegerField(choices=[(1, 'Wall'), (2, 'Door'), (3, 'Open Space'), (4, 'Counter/Half-wall')], default='Door')),
                ('side', models.PositiveSmallIntegerField(choices=[(1, 'Left'), (2, 'Right'), (3, 'Top'), (4, 'Bottom')], default='Left')),
                ('first_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_room', to='operations.Room')),
                ('second_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_room', to='operations.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('recycle', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=False)),
                ('condition_relations', models.CharField(max_length=50)),
                ('conditions', models.ManyToManyField(to='operations.Condition')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_connections',
            field=models.ManyToManyField(related_name='_room_room_connections_+', through='operations.RoomConnection', to='operations.Room'),
        ),
        migrations.AddField(
            model_name='group',
            name='lights',
            field=models.ManyToManyField(related_name='grouped_in', through='operations.LightGroup', to='MachineInterface.Light'),
        ),
        migrations.AddField(
            model_name='action',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Rule'),
        ),
    ]
