# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='devices',
        ),
        migrations.AddField(
            model_name='group',
            name='api',
            field=models.CharField(default='softhome', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='controller_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inside', to='operations.Room'),
        ),
        migrations.AlterField(
            model_name='group',
            name='classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='lights',
            field=models.ManyToManyField(blank=True, null=True, related_name='grouped_in', through='operations.LightGroup', to='MachineInterface.Light'),
        ),
    ]
