# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ssid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
