# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_auto_20170122_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ssid',
        ),
        migrations.AddField(
            model_name='device',
            name='api',
            field=models.CharField(default='softhome', max_length=100),
        ),
    ]
