# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Portal', '0001_initial'),
        ('MachineInterface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.PositiveSmallIntegerField(default=0)),
                ('ct', models.PositiveSmallIntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('light_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachineInterface.Light')),
            ],
        ),
        migrations.CreateModel(
            name='LightSensorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachineInterface.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='MotionSensorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachineInterface.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='OutletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('outlet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachineInterface.Outlet')),
            ],
        ),
        migrations.CreateModel(
            name='SoundSensorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('recording', models.FileField(max_length=200, upload_to='')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachineInterface.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSensorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachineInterface.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='WIFIHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('signal_strength', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('SSID', models.CharField(max_length=200)),
                ('connection_time', models.DateTimeField(auto_now=True)),
                ('gps_dd', models.CharField(max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Device')),
            ],
        ),
    ]
