# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lighthistory',
            old_name='light_id',
            new_name='light',
        ),
        migrations.RenameField(
            model_name='lightsensorhistory',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='motionsensorhistory',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='outlethistory',
            old_name='outlet_id',
            new_name='outlet',
        ),
        migrations.RenameField(
            model_name='soundsensorhistory',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='temperaturesensorhistory',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='wifihistory',
            old_name='SSID',
            new_name='ssid',
        ),
        migrations.AddField(
            model_name='lighthistory',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
