# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('brightness', models.PositiveSmallIntegerField(default=0)),
                ('ct', models.PositiveSmallIntegerField(default=0)),
                ('alert', models.CharField(blank=True, max_length=50, null=True)),
                ('reachable', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('model_id', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('primary_controller', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_controller', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Device')),
            ],
        ),
        migrations.CreateModel(
            name='PhilipsHueBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_id', models.CharField(max_length=100)),
                ('swversion', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('ct', models.PositiveSmallIntegerField(default=0)),
                ('brightness', models.PositiveSmallIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('state', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(max_length=100)),
                ('timelapse', models.FileField(max_length=200, upload_to='')),
                ('reachable', models.BooleanField(default=False)),
                ('model_id', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('primary_controller', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Device')),
            ],
        ),
        migrations.CreateModel(
            name='WIFILocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('signal_strength', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('ssid', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('gps_dd', models.CharField(max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.Device')),
            ],
        ),
    ]
