# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineInterface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifilocation',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='wifilocation',
            name='ssid',
        ),
        migrations.AddField(
            model_name='outlet',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='philipshuebridge',
            name='bridge_user',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
