# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_auto_20170202_0002'),
        ('MachineInterface', '0003_auto_20170123_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='device',
        ),
        migrations.RemoveField(
            model_name='light',
            name='id',
        ),
        migrations.RemoveField(
            model_name='light',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='light',
            name='name',
        ),
        migrations.RemoveField(
            model_name='light',
            name='primary_controller',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='device',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='philipshuebridge',
            name='device',
        ),
        migrations.RemoveField(
            model_name='philipshuebridge',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='device',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='primary_controller',
        ),
        migrations.RemoveField(
            model_name='wifilocation',
            name='device',
        ),
        migrations.RemoveField(
            model_name='wifilocation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wifilocation',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='light',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_light', to='Portal.Device'),
        ),
        migrations.AddField(
            model_name='light',
            name='controller_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='light',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Portal.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_outlet', to='Portal.Device'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Portal.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='philipshuebridge',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Portal.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_sensor', to='Portal.Device'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='controller_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Portal.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wifilocation',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Portal.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wifilocation',
            name='ssid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='primary_controller',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='timelapse',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
