# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_auto_20170202_0002'),
        ('MachineInterface', '0004_auto_20170202_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='ct',
        ),
        migrations.RemoveField(
            model_name='light',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='philipshuebridge',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='wifilocation',
            name='device_ptr',
        ),
        migrations.AddField(
            model_name='light',
            name='color_cie_xy',
            field=models.CharField(default='[0.31306, 0.32318]', max_length=100),
        ),
        migrations.AddField(
            model_name='light',
            name='color_temperature',
            field=models.PositiveSmallIntegerField(default=153),
        ),
        migrations.AddField(
            model_name='light',
            name='colormode',
            field=models.CharField(default='ct', max_length=100),
        ),
        migrations.AddField(
            model_name='light',
            name='device',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='light_device', serialize=False, to='Portal.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='light',
            name='type',
            field=models.CharField(default='Color temperature light', max_length=100),
        ),
        migrations.AddField(
            model_name='outlet',
            name='device',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='outlet_device', serialize=False, to='Portal.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='philipshuebridge',
            name='device',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='philips_device', serialize=False, to='Portal.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='picture',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sensor',
            name='device',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sensor_device', serialize=False, to='Portal.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wifilocation',
            name='device',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='wifi_device', serialize=False, to='Portal.Device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='light',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='light_controller', to='Portal.Device'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_controller', to='Portal.Device'),
        ),
    ]
