# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineInterface', '0005_auto_20170205_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
